# AlertManager configuration for RAG System
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@your-domain.com'

# Route alerts to different receivers
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

# Alert receivers
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:8000/api/v1/webhooks/alerts'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@your-domain.com'
        subject: '[CRITICAL] RAG System Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Labels: {{ range .Labels.SortedPairs }}
          - {{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}
    webhook_configs:
      - url: 'http://localhost:8000/api/v1/webhooks/alerts'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'monitoring@your-domain.com'
        subject: '[WARNING] RAG System Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Labels: {{ range .Labels.SortedPairs }}
          - {{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}

# Inhibit rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']