apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      customQueryParameters: ''
      incrementalQuerying: false
      intervalFactor: 2
      keepCookies: []
      nodeGraph:
        enabled: true
      exemplarTraceIdDestinations: []
      
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
          
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:14268
    uid: jaeger
    isDefault: false
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          {
            key: 'service.name',
            value: 'service'
          }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
        
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ragdb
    user: raguser
    isDefault: false
    editable: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgres_version: 1500
      timescaledb: false
      
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    isDefault: false
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
      
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    editable: true
    database: '[logs-*]'
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: 8
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
      includeFrozen: false
      
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: true
    database: ragdb
    user: raguser
    jsonData:
      version: Flux
      organization: rag-system
      defaultBucket: metrics
      tlsSkipVerify: false
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
