name: Build Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deployment/requirements/simple_requirements.txt
        # Install package in development mode for proper imports
        pip install -e .
    
    - name: Install optional dependencies
      continue-on-error: true
      run: |
        pip install redis
        pip install psycopg2-binary
    
    - name: Check Python syntax
      run: |
        python -m py_compile core/main.py
        python -m py_compile core/ollama_client.py
        python -m py_compile simple_api.py
        echo "Python syntax check passed"
    
    - name: Basic import test
      run: |
        export PYTHONPATH="$(pwd):${PYTHONPATH}"
        python -c "import core.main; print('Core imports successful')"
        python -c "import core.ollama_client; print('Ollama client imports successful')"